# Generated by Django 4.2.1 on 2023-05-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Software Developer', 'Software Developer'), ('Software Tester', 'Software Tester'), ('Project Leader', 'Project Leader')], max_length=100),
        ),
    ]
